### ISSUE TITLE
mcore number in command vs config

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/pipeline-nanopore-denovo-isoforms#10]
Hi,

I wonder how does the num_cores value given in the command 

```snakemake -j <num_cores> all```

relates to the built-in value present in the config.yaml file

```
## Pipeline-specific parameters:
cores: 20
```

When using 80 threads, should I only adapt the first command or also adapt the yaml?
Should the yaml count be a divider of the total thr count, eg 80 & 20 allowing four 'batches' of 20 ?
Finally, how many GB of RAM should be present for each declared thread for the pipeline to run optimally?

Thanks in advance

**Comment by bsipos** [comment]
Hello!

The "cores" parameter in the YAML file determines how many initial batches will be created from the sorted input reads and hence the number of the initial clustering jobs. The fewer the number of the batches, the more resources each initial clustering job will consume (CPU and memory). 
The `-j` parameter on the other hand determines the number of parallel jobs allowed by `snakemake` - the more jobs, the more resources required for the run.
Please consider these factors when setting these parameters. If you have a large dataset it makes sense to run your analysis on an SGE cluster.
