### ISSUE TITLE
Creating a consensus fasta file with unique transcripts

### ISSUE THREAD

**Issue by ALSP6OCT** [nanoporetech/pipeline-nanopore-denovo-isoforms#4]
Hello,
Is it possible to create a de novo transcriptome fasta file with unique transcripts, with this pipeline? I would like to use it to further map other samples against this reference transcriptome.
Thanks in advance for your help.

**Comment by bsipos** [comment]
Hello! This is not a feature of the pipeline - so far it only clusters reads into gene families.
