### ISSUE TITLE
'Workflow' object has no attribute 'overwrite_configfiles'

### ISSUE THREAD

**Issue by splaisan** [nanoporetech/pipeline-nanopore-denovo-isoforms#5]
I edited in config.yml to point to my fastq (no other edits)

```
# cDNA or direct RNA reads in fastq format
reads_fastq: "/data/NC_projects_GridION/Flongle/reads.fq"
```

[config.yml.txt](https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms/files/5433376/config.yml.txt)

then when I run (I have 88 cores) I get

```
snakemake -j 88 all
AttributeError in line 12 of /opt/biotools/pipeline-nanopore-denovo-isoforms/Snakefile:
'Workflow' object has no attribute 'overwrite_configfiles'
  File "/opt/biotools/pipeline-nanopore-denovo-isoforms/Snakefile", line 12, in <module>
```

same error with snakemake -j 20 all

Thanks in advance for your help

**Comment by claumer** [comment]
Exactly the same problem here.

(base) [claumer@hx-noah-13-10 pipeline-nanopore-denovo-isoforms]$ snakemake -j 8 all
AttributeError in line 12 of /nfs/research1/marioni/claumer/pipeline-nanopore-denovo-isoforms/Snakefile:
'Workflow' object has no attribute 'overwrite_configfiles'
  File "/nfs/research1/marioni/claumer/pipeline-nanopore-denovo-isoforms/Snakefile", line 12, in <module>

**Comment by splaisan** [comment]
> Weirdly though, it took changing:
> 
> if not workflow.overwrite_configfiles:
> 
> to
> 
> if not workflow.overwrite_configfile:

thanks a lot for that catch @claumer !, now running for me too...

**Comment by splaisan** [comment]
Stopped a little further, opening a separate issue
