### ISSUE TITLE
Error in the clustering step with isONclust2 cluster

### ISSUE THREAD

**Issue by amarosaco** [nanoporetech/pipeline-nanopore-denovo-isoforms#9]
Hello,
We are trying to apply this pipeline to our set of reads (aprox. 7 million cDNA reads from a transcriptomic experiment).
We succesfully reach the clustering step (batches step works well, obtaining 16 isONbatch files).
However, after doing this, the script fails with this output error:

Error in rule cluster_job_3:
    jobid: 20
    output: clusters/isONcluster_3.cer
    shell:
        isONclust2 cluster -x sahlin -v -Q -l sorted/batches/isONbatch_3.cer -o clusters/isONcluster_3.cer -z; sync
        (exited with non-zero exit code)

Then, our computer crashes and, after we stop the process, we obtain the same error for the other batches.
I attach the logfile of the script, and both the Snakefile and configfile.
I hope you can help us.
Thank you in advance.

[logfile script.txt](https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms/files/5492896/logfile.script.txt)
[config.txt](https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms/files/5492897/config.txt)
[Snakefile.txt](https://github.com/nanoporetech/pipeline-nanopore-denovo-isoforms/files/5492898/Snakefile.txt)

**Comment by bsipos** [comment]
Hello!

isONclust2 analyses can be quite memory demanding - make sure sure that you have enough to run it or better run it on a larger SGE/UGE cluster.
